name: "IR Learner Exporter"
version: "0.2.0"
slug: "ir_learner_exporter"
description: >-
  Interface web Ingress pour apprendre des codes IR, générer automatiquement
  des combinaisons clim, importer/exporter un JSON type Broadlink/AC.
url: "https://github.com/TON_USER/TON_REPO"
arch:
  - amd64
  - aarch64
  - armv7
  - i386
startup: application
boot: manual
init: false

ingress: true
ingress_port: 8099
panel_icon: mdi:remote-tv
panel_title: IR Learner
panel_admin: true

map:
  - type: addon_config
    read_only: false
  - type: data

ports:
  8099/tcp: null

ports_description:
  8099/tcp: Web UI interne utilisée par Ingress

options:
  export_filename: learned_codes.json
  default_manufacturer: ""
  default_supported_controller: Broadlink

schema:
  export_filename: str
  default_manufacturer: "str?"
  default_supported_controller: "list(Broadlink)"