name: "IR Learner Exporter"
version: "0.2.45"
slug: "ir_learner_exporter"
description: "UI Ingress pour générer un JSON de codes IR"
arch:
  - amd64
  - aarch64
  # armv7 et i386 sont dépréciés sur certaines versions Home Assistant
  # les retirer si vous ne les utilisez pas pour éviter le warning
startup: application
boot: manual
init: false
build: true

homeassistant_api: true

ingress: true
ingress_port: 8099
panel_icon: mdi:remote-tv
panel_title: IR Learner
panel_admin: true

map:
  - type: addon_config
    read_only: false
  - type: data
  # Lecture du dossier config de HA pour récupérer les codes Broadlink après apprentissage (.storage).
  - type: homeassistant_config
    read_only: true

options:
  export_filename: "learned_codes.json"
  default_manufacturer: ""
  default_supported_controller: "Broadlink"
  learn_timeout_seconds: 40

schema:
  export_filename: str
  default_manufacturer: str?
  default_supported_controller: str
  learn_timeout_seconds: int